##############################################################################
## Provision bind
## This role executes much of the needed functionality to provision an
## application using an Ansible Playbook Bundle.  Included in the comments
## below are some sample resources for getting started deploying an application
## to OpenShift.
##############################################################################


- name: render config template
  template:
    src: named.conf.j2
    dest: /tmp/named.conf


- name: create config map
  k8s_v1_config_map:
    name: bind-config
    namespace: '{{ namespace }}'
    data:
      named.conf: "{{ lookup('file', '/tmp/named.conf') }}"


- name: create deployment config
  openshift_v1_deployment_config:
    name: bind
    namespace: '{{ namespace }}'
    labels:
      app: bind
      service: bind
    replicas: 1
    selector:
      app: bind
      service: bind
    spec_template_metadata_labels:
      app: bind
      service: bind
    containers:
    - env:
      image: docker.io/mhrivnak/bind
      name: bind
      ports:
      - container_port: 5053
        protocol: TCP
      - container_port: 5053
        protocol: UDP
      volumeMounts:
        - name: bind-config
          mountPath: /var/run/secrets/bind/config/
    volumes:
      - name: bind-config
        configMap:
          name: bind-config


- name: create bind service
  k8s_v1_service:
    name: bind
    namespace: '{{ namespace }}'
    labels:
      app: bind
      service: bind
    selector:
      app: bind
      service: bind
    ports:
      - name: dns
        port: 53
        target_port: 5053
        protocol: UDP
    type: LoadBalancer
